networks:
  kspeeder_default:
    external: true
    name: "kspeeder_default"
    driver: bridge
    enable_ipv6: true # 启用IPv6支持 [[5]][[9]]
    ipam:
      config:
        - subnet: 240.172.0.0/24 # IPv4子网 [[2]]
          gateway: 240.172.0.1
        - subnet: fc01:db8:1::/64 # IPv6子网（示例，需符合实际网络规划）
          gateway: fc01:db8:1::1

services:
  crontab-guru-dashboard:
    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"

    command:
      - "bash"
      - "-c"
      - "cronitor configure --dash-username $YOUR_USERNAME_HERE --dash-username $YOUR_PASSWORD_HERE &&\
        \ cronitor dash --port 9000"

    container_name: "crontab-guru-dashboard"

    entrypoint:
      - "docker-entrypoint.sh"

    environment:
      - "YOUR_USERNAME_HERE=rcz4j3xn9cdbffxohg0vk6xvodecqlfjc8dk5vau2dag0f9cst"
      - "YOUR_PASSWORD_HERE=xwplse6d0lqz2yo12kq8zlbios5h6dhxdsn416rvnzdlrad00i"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "NODE_VERSION=22.19.0"
      - "YARN_VERSION=1.22.22"
      - "TZ=Asia/Shanghai"
      - "TELEMETRY=off"

    hostname: "28672ed33e64"

    image: "docker.cnb.cool/masx200/docker_mirror/crontab-guru-dashboard:latest"

    ipc: "private"

    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"

    networks:
      - "kspeeder_default"

    ports:
      - "10000:9000/tcp"

    privileged: true

    restart: "always"

    security_opt:
      - "label=disable"

    stdin_open: true

    tty: true

    volumes:
      - "/vol1/1000/crontab-guru-dashboard/etc/cronitor:/etc/cronitor"
      - "/vol1/1000/crontab-guru-dashboard/root/.config/cronitor:/root/.config/cronitor"
      - "/vol1/1000/crontab-guru-dashboard/var/spool/cron/crontabs:/var/spool/cron/crontabs"
      - "/vol1/1000/immich-cli/root/.config/immich:/root/.config/immich"
      - "/vol1/1000/飞牛相册/MobileBackup:/vol1/1000/飞牛相册/MobileBackup"

    working_dir: "/app"

version: "3.6"
